============ upmed-api Unit Test Report Generated on 1605841932 ============ \n\n
........
----------------------------------------------------------------------
Ran 8 tests in 0.004s

OK
/usr/lib/python3.6/runpy.py:125: RuntimeWarning: 'upmed-api.tst.api.hcp_test.hcp_test' found in sys.modules after import of package 'upmed-api.tst.api.hcp_test', but prior to execution of 'upmed-api.tst.api.hcp_test.hcp_test'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
............
----------------------------------------------------------------------
Ran 12 tests in 0.006s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 1.378s

OK
